# Enable H2 Database Engine
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

server.port=8082

# Enable the H2 Web Console to inspect your generated tables
spring.h2.console.enabled=true

# Crucial for Auto-Generation matching your Model Schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8InnoDBDialect
#spring.jpa.hibernate.ddl-auto=update
